version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    resource_class: "windows.medium"
    machine:
      image: 'windows-server-2022-gui:current'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: addpath(genpath(pwd));
      - matlab/run-command:
          command: addpath(genpath('../'));